### ISSUE TITLE
如何添加 应用到 OkHttp 的 addInterceptor将返回信息自动格式化

### ISSUE THREAD

**Issue by BaiMingxu1** [liangjingkanji/LogCat#1]

**Comment by liangjingkanji** [comment]
这个框架没有这个功能, 建议使用[Net](https://liangjingkanji.github.io/Net/log-recorder/#_4)中的日志输出功能配合AndroidStudio的插件使用(不要求一定使用Net网络请求)
效果图
![](https://i.imgur.com/PJsaKpx.png)

**Comment by liangjingkanji** [comment]
未来计划中
